version: '3'

services:
  python-app:
    build: .
    env_file:
      - ./config/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./config/.env
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:
